- core/src/app/components/settings/settings.component.html
- core/src/app/components/settings/settings.component.ts
- core/src/assets/i18n/en.json
- core/src/assets/i18n/en.ts
- core/src/assets/i18n/fr.json
- core/src/assets/i18n/fr.ts
- core/src/assets/i18n/it.json
- core/src/assets/i18n/it.ts
Include a new button in the settings component for accessing the privacy page. Update language files accordingly. feat: add privacy link to settings component
Include a new button in the settings component for accessing the privacy page. Update language files accordingly.
> chore: add privacy link to settings component

- core/src/assets/i18n/it.json
- core/src/assets/i18n/it.ts
Include translation for 'cai_scale' in the Italian language file.
> chore: Add 'cai_scale' translation to Italian language file oc: 4097

- core/src/app/pages/waypoint/modal-waypoint-save/modal-waypoint-save.component.html
- Changed the back button to use an ion-button with a chevron-back icon
- Updated the color of the button to dark
> chore: Update modal-waypoint-save.component.html oc: 3938

- core/src/app/pages/register/register.page.html
- core/src/app/pages/register/register.page.scss
- Added a new map component
- Updated the layout of the bottom buttons
- Adjusted the position and style of the orientation button
> chore: Update register page UI oc: 4103

- core/src/app/components/poi-properties/poi-properties.component.html
Include an excerpt component in the POI properties view. This enhancement allows for better presentation of property information by displaying excerpts when available.
> chore(poi-properties): add excerpt display to properties oc: 4183

- core/src/app/pages/register/modal-save/modal-save.component.ts
This commit updates the code in modal-save.component.ts file. The changes include:
- Importing the 'from' and 'Observable' functions from the 'rxjs' library.
- Adding the 'saveUgcTrack' function to the import statement from '@wm-core/utils/localForage'.
- Importing the 'take' and 'switchMap' functions from the 'rxjs/operators' library.
- Adding the '_store' parameter to the constructor of ModalSaveComponent.
- Modifying the backToSuccess() method to return a Promise<boolean> instead of void.
- Modifying the saveTrack() method to use observables and dispatch actions using Redux store.
These changes aim to improve code functionality and maintainability.
> chore: Update modal-save.component.ts oc: 4608

- core/package-lock.json
- core/package.json
- core/src/app/components/cards/card-track/card-track.component.ts
- core/src/app/pages/downloadlist/downloadlist.page.html
- core/src/app/pages/downloadlist/downloadlist.page.ts
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.scss
- core/src/app/pages/map/map.page.ts
- Updated imports in card-track.component.ts to include LineString from geojson.
- Updated types of track input and output events in card-track.component.ts to use WmFeature<LineString>.
- Updated types of selected and tracks arrays in downloadlist.page.ts to use WmFeature<LineString>.
- Removed unused import GeoJSONFeature from downloadlist.page.ts.
- Updated types of track input and output events in downloadlist.page.html to use WmFeature<LineString>.
chore: update dependencies
- Updated "@tmcw/togeojson" to version 6.0.0
- Added new dependency "xmldom" version 0.6.0
- Updated "@jridgewell/gen-mapping" to version 0.3.3
- Updated "@jridgewell/resolve-uri" to version 3.1.1
> chore: Update card-track.component.ts and downloadlist.page.ts oc:4740,4745,4739,4741,4727

- core/src/app/pages/map/map-details/map-details.component.scss
- core/src/app/pages/map/map.page.html
- Adjusted the top position of ion-card-content in map-details.component.scss
- Added a ng-template block for wm-track-properties in map.page.html
> chore: Update map-details.component.scss and map.page.html oc: 4735

- core/src/app/pages/favourites/favourites.page.ts
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.ts
- Added a new ng-container in the HTML file to display a favorite button for authenticated users
- Updated the TypeScript file to handle the favorite button functionality by checking if a track is already marked as favorite
> chore: Update map page HTML and TypeScript files oc: 4757

- core/src/app/components/settings/settings.component.html
- core/src/app/components/settings/settings.component.ts
- core/src/assets/i18n/en.json
- core/src/assets/i18n/en.ts
- core/src/assets/i18n/fr.json
- core/src/assets/i18n/fr.ts
- core/src/assets/i18n/it.json
- core/src/assets/i18n/it.ts
- Added a note to inform the user about enabling location permission in settings
- Added a button to open the app settings
- Updated the translation for distance filter information
chore(i18n): Add translations for recording tracks and opening app settings
- Added translations for the phrases "To record tracks and display them correctly, enable the location permission in the settings" and "Open app settings" in English, French, and Italian.
- Updated the JSON and TypeScript files for each language to include the new translations.
> chore: Update settings component oc:4750

- core/src/app/pages/map/map-details/map-details.component.ts
- Added gesturePriority property to the drag handle icon
- Set passive property to false in the gesture configuration
- Prevented default event behavior in onStart and onEnd functions
> chore: Update map-details.component.ts oc:4853

- core/src/app/components/poi-properties/poi-properties.component.html
- core/src/app/components/poi-properties/poi-properties.component.scss
- core/src/app/pages/map/map.page.html
- Replace wm-image-gallery with wm-tab-image-gallery
- Move address, elevation, phone, email, and related URLs components inside a div with class "wm-poi-properties-info"
- Remove unnecessary CSS styles in the SCSS file
chore: Update map page HTML
- Renamed CSS class from "webmapp-track-download-urls-item" to "wm-track-useful-urls-item"
- Changed ion-icon name from "wm-icn icon-link" to "link-outline"
- Updated ion-label text from "{{'apri pdf'|wmtrans}}" to "{{'Apri pdf'|wmtrans}}"
chore: Update poi-properties.component.html
- Refactored the code to use wm-tab-detail component for displaying address, elevation, phone, email, and related URLs.
- Moved wm-phone, wm-email, and wm-related-urls components inside wm-track-useful-urls component.
chore: Update poi-properties.component.html
- …
> - Refactor HTML structure for better organization and readability oc: 4837

- core/src/app/app.component.ts
- Imported Observable and from from the rxjs library
- Added a subscription to getUgcLoadedOnce() and dispatched setUgcLoaded action if ugcLoadedOnce is true
> chore: Update app.component.ts oc:4791

- core/cypress.config.ts
- core/package-lock.json
- core/package.json
- Added cypress.config.ts file
- Updated package-lock.json to include new dependencies
> chore: Add cypress.config.ts and update package-lock.json

- core/src/app/components/poi-properties/poi-properties.component.html
- core/src/app/components/poi-properties/poi-properties.component.ts
- core/src/app/pages/map/map.page.html
- Added conditional rendering for wm-tab-detail and wm-feature-useful-urls based on the values of showTechnicalDetails$ and showUsefulUrls$
- Updated set properties method to update the values of showTechnicalDetails$ and showUsefulUrls$
> chore: Update poi-properties component oc:4837

- core/cypress/e2e/app_52/orientation-and-location-buttons.cy.ts
Added a new e2e test file to test the visualization of the orientation and location buttons. The test verifies that the buttons are displayed correctly on the map page.
> feat: add e2e test for orientation and location buttons oc: 4989

- core/cypress/e2e/app_52/flow-line-quote.cy.ts
This commit adds the flow line quote feature to the application. It includes a new file `flow-line-quote.cy.ts` that contains the implementation for displaying the flow line quote. The feature allows users to see different levels of altitude based on specific criteria. The implementation includes fetching configuration data from an API endpoint, updating the UI with the fetched data, and handling user interactions with the flow line quote.
The `Flow line quote` test suite verifies that the flow line quote is displayed correctly based on different altitude levels. It simulates user interactions by clicking on specific areas of a canvas and asserts that the correct level description is shown in the UI.
This feature enhances the user experience by providing valuable information about …
> chore: add flow line quote feature oc:4955

- core/cypress/e2e/app_52/distance-and-duration-filters.cy.ts
- core/cypress/utils/test-utils.ts
This commit adds the necessary code to implement distance and duration filters in the app_52 module. The filters allow users to specify a range for both distance and duration when searching for tracks.
> chore: add distance and duration filters test oc:4925

- core/src/app/pages/map/map-details/map-details.component.html
- core/src/app/pages/map/map-details/map-details.component.scss
- core/src/app/pages/map/map-details/map-details.component.ts
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.ts
chore: Update map-details component
- Updated the click event for the close button in the HTML template
- Updated the selector for wm-search-box in the SCSS file
- Updated the selectors for ion-card and ion-card-header in the SCSS file
- Added a new import statement for setMapDetailsStatus action in the TypeScript file
- Added a new method clickBack() to handle click event on back button
chore: Update map page HTML and TypeScript files
- Refactor the HTML code to use ng-container instead of div for conditional rendering
- Add featureOpened$ observable to the TypeScript file
Updated submodule core/src/app/shared/wm-core
> chore: update layers view oc: 5162

- core/src/app/pages/map/map-details/map-details.component.html
- core/src/app/pages/map/map-details/map-details.component.scss
- core/src/app/pages/map/map-details/map-details.component.ts
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.scss
- core/src/app/pages/map/map.page.ts
chore: Update map-details component
- Updated the click event for the back button
- Added border-radius to the map details component
- Adjusted the margin-top and border-radius for certain elements in the SCSS file
- Removed unused output events from the component
- Modified the logic for handling different map details statuses
chore: Update wm-status-filter in map page
- Added event listener for removeLayerEVT to close details
- Updated setMapDetailsStatus dispatch to backOfMapDetails
- Added closeDetails method to dispatch backOfMapDetails
Updated submodule core/src/app/shared/wm-core
chore: Update map page HTML and SCSS
- Added conditional class "only-title" to wm-map-details element in map.page.html
- Updated styles for wm-status-filter element in map.page.scss
chore: Update map page …
> chore: update layers view oc:5203

- core/src/app/components/poi-properties/poi-properties.component.html
- core/src/app/components/poi-properties/poi-properties.component.scss
- core/src/app/components/poi-properties/poi-properties.component.ts
- core/src/app/pages/map/map-details/map-details.component.scss
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.scss
- Added ion-label to display distance from current location
- Added wm-poi-types-badges to display poi types
- Added wm-get-directions component
- Updated styling for ion-label and wm-poi-properties-info
> chore: Update poi-properties component oc:5275

- core/src/app/components/poi-properties/poi-properties.component.html
- Added ngIf condition to display distance from current POI
- Removed unnecessary async pipe for distanceFromCurrentPoi
> chore: Update poi-properties.component.html oc:5333

- core/src/app/pages/map/map-details/map-details.component.scss
- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.ts
- core/src/app/pages/tabs/tabs.page.ts
- Added styles for wm-image-detail component in map-details.component.scss
- Updated conditional rendering of header div in map.page.html based on currentEcImageGalleryIndex$ value
- Updated queryParams object in tabs.page.ts to include the layer parameter
> chore: Update map-details.component.scss, map.page.html, and tabs.page.ts oc:5298

- core/src/app/app.component.ts
- core/src/app/app.module.ts
- Removed setting translations for Italian, English, and French languages in the app component.
- Added translations for Italian, English, and French languages in the app module using the new APP_TRANSLATION token.
> chore: Update translations in app component and app module oc: 5343

- core/src/app/pages/map/map.page.html
- core/src/app/pages/map/map.page.scss
- core/src/app/pages/map/map.page.ts
- Updated the ion-content element in map.page.html to use [ngClass] instead of [class.full-details] and [class.only-title]
- Added a new class .has-feature-in-viewport in map.page.scss with a transform property for .bottom-right:first-of-type
- Updated map.page.ts to include the hasFeatureInViewport$ observable from the store
> chore: Update map page HTML and SCSS oc:5363

- core/src/app/pages/profile/profile.page.ts
- core/src/assets/i18n/de.json
- core/src/assets/i18n/en.json
- core/src/assets/i18n/es.json
- core/src/assets/i18n/fr.json
- core/src/assets/i18n/it.json
- core/src/assets/i18n/pr.json
- core/src/assets/i18n/sq.json
fix: change TranslationService with LangService
> chore: add translation for profile.pages.ts oc:5454
